### ISSUE TITLE
[Feature] Create a Linux version

### ISSUE THREAD

**Issue by Grabt234** [Sense-Scape/Windows_Proc_Serv#15]
Windows version is gonna die :)

supporting windows and linux is probably a bad idea

**Comment by wolffshots** [comment]
`cmake` version should be usable on windows anyways

**Comment by Grabt234** [comment]
yep, want to kill windows version though, no need for it with WSL - it simplifies all code management and building if everything is restricted to linux

**Comment by wolffshots** [comment]
what I’m saying is that you’re not killing windows support by killing msbuild support. i agree that just supporting `cmake` simplifies stuff
